pipeline {
    agent any

    environment {
        PYENV_HOME = "${WORKSPACE}/welcome/app/flask-volt-dashboard/.pyenv"
        PROJECT_HOME = "${WORKSPACE}/welcome/app/flask-volt-dashboard"
        FLASK_APP = 'run.py'
        FLASK_ENV = 'development'
    }

    stages {
        stage('Clone Flask Project') {
            steps {
                // Use the Git plugin to clone the repository
                git branch: 'jenkins-workshop', url: 'https://github.com/yanivomc/devopshift-welcome.git'
            }
        }

        stage('Setup Python Environment and Install Dependencies') {
            steps {
                dir("${PROJECT_HOME}") {
                    script {
                        sh '''#!/bin/bash
                        if ! command -v virtualenv &> /dev/null; then
                            echo "Installing virtualenv..."
                            pip install virtualenv
                        fi

                        rm -rf $PYENV_HOME
                        virtualenv $PYENV_HOME
                        source $PYENV_HOME/bin/activate

                        pip install -r requirements.txt
                        '''
                    }
                }
            }
        }

        stage('Run Flask Application') {
            steps {
                dir("${PROJECT_HOME}") {
                    script {
                        sh '''#!/bin/bash
                        source $PYENV_HOME/bin/activate
                        tasks=$(pgrep -f "flask run")
                        if [ -n "$tasks" ]; then
                            echo "Stopping existing Flask application..."
                            for pid in $tasks; do
                                kill -9 $pid
                                echo "Killed process $pid"
                            done
                        fi

                        echo "Starting Flask application on 0.0.0.0:5001..."
                        nohup flask run --host=0.0.0.0 --port=5001 > flask_app.log 2>&1 &
                        '''
                    }
                }
            }
        }

        stage('Verify Application') {
            steps {
                dir("${PROJECT_HOME}") {
                    script {
                        sleep 5
                        def tasks = sh(script: "pgrep -f 'flask run'", returnStatus: true) ? '' : sh(script: "pgrep -f 'flask run'", returnStdout: true).trim()
                        if (!tasks) {
                            echo "There is a problem with our flask application - printing log below"
                            sh 'cat flask_app.log'
                            error "Flask application is not running!"
                        } else {
                            echo "Flask application is running successfully."
                        }
                    }
                }
            }
        }

        stage('Manual QA Approval') {
            steps {
                script {
                    def userInput = input message: 'Is the application running successfully? ',
                                         parameters: [choice(name: 'Proceed', choices: 'Proceed\nAbort', description: 'use the URL: http://REMOTEIP:5001 and Choose an option')]
                    env.USER_CHOICE = userInput
                }
            }
        }

        stage('Automated Tests') {
            when {
                expression { env.USER_CHOICE == 'Proceed' }
            }
            steps {
                script {
                    echo 'Running automated tests...'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                dir("${PROJECT_HOME}") {
                    echo 'Archiving Flask log file...'
                    archiveArtifacts artifacts: 'flask_app.log', allowEmptyArchive: true
                }
            }
        }

        stage('Failed Manual QA Approval') {
            when {
                expression { env.USER_CHOICE == 'Abort' }
            }
            steps {
                script {
                    error 'Pipeline aborted by the user'
                }
            }
        }

        stage('Finalize the Pipeline') {
            steps {
                script {
                    if (env.USER_CHOICE == 'Proceed') {
                        echo 'Manual QA and automated tests approved, pipeline completed successfully'
                    } else {
                        echo 'Pipeline aborted by the user'
                    }
                }
            }
        }
    }

    post {
        always {
            dir("${PROJECT_HOME}") {
                echo 'Cleaning up workspace...'
                sh 'rm -rf $PYENV_HOME'
            }
        }
    }
}

